{% set name = "polars-hash" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polars_hash-{{ version }}.tar.gz
    sha256: b43841c178b67a0d4b63108a77a110fb0a5e3ed22245cb615d48d3528d5c549a
  - url: https://raw.githubusercontent.com/ion-elgreco/polars-hash/main/LICENSE
    sha256: 017feb4ae87126410f1d9beb6af4c9df3c25a0051d87db66da6f26c509f5348d

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - polars >=0.20.16

test:
  imports:
    - polars_hash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ion-elgreco/polars-hash
  summary: Stable non-cryptographic and cryptographic hashing functions for Polars
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
